# docker-compose.yml
services:
  litellm:
    image: ghcr.io/berriai/litellm:main
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - LITELLM_LOG=INFO
      - OLLAMA_URL=${OLLAMA_URL:-http://172.17.0.1:11434}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    volumes:
      - ./litellm/config.yaml:/app/config.yaml:ro
    command: ["--port", "4000", "--config", "/app/config.yaml"]
    profiles:
      - litellm
  typesense:
    image: typesense/typesense:0.25.1
    restart: unless-stopped
    ports:
      - "8108:8108" # Expose YOUR Typesense instance locally
    volumes:
      - typesense-data:/data # Your data stays local
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz123abc} # Auth for YOUR local instance
      - TYPESENSE_ENABLE_CORS=true
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"

  scraper:
    build: ./scraper
    depends_on:
      - typesense
    environment:
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz123abc}
      - TARGET_URL=${TARGET_URL:-https://my.gov.au}
      - MAX_DEPTH=${MAX_DEPTH:-3}
      - MAX_LINKS_PER_PAGE=${MAX_LINKS_PER_PAGE:-10}
      - CONCURRENCY=${CONCURRENCY:-5}
    volumes:
      - ./scraper:/app
      - /app/node_modules # This preserves node_modules from the image
      - ./config:/config # Mount config at root level
      - ./data:/data

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - typesense
    environment:
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz123abc}
      - PORT=${PORT:-3000}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - OLLAMA_URL=${OLLAMA_URL:-http://172.17.0.1:11434}
      - ENABLE_LITELLM=${ENABLE_LITELLM:-false}
      - LITELLM_URL=${LITELLM_URL:-http://litellm:4000}
      - LITELLM_API_KEY=${LITELLM_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    volumes:
      - ./api:/app
      - /app/node_modules # This preserves node_modules from the image
      - ./config:/config # Mount config at root level

volumes:
  typesense-data:

networks:
  default:
    name: mygov-net
